---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: chittaranjan-chandwani
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "chittaranjan27/devops_scientific_calculator"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name  devops_scientific_calculator chittaranjan27/devops_scientific_calculator
